---
base_reboot_time: "01:00"
firewall_allowed:
  - name: wireguard
    proto: udp
    port: 51820
    from: any
  - name: http
    proto: tcp
    port: 80
    from: any
  - name: https
    proto: tcp
    port: 443
    from: any
